spring:
  application:
    name: eureka-server
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000